campus_event_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from stations.views import CustomLoginView, CustomLogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stations.urls')),
    path('accounts/login/', CustomLoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout/', CustomLogoutView.as_view(template_name='registration/logout.html'), name='logout'),
]

stations/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('events/', views.event_list, name='event_list'),
    path('events/<int:event_id>/', views.event_detail, name='event_detail'),
    path('events/create/', views.event_create, name='event_create'),
    path('events/<int:event_id>/edit/', views.event_edit, name='event_edit'),
    path('events/<int:event_id>/delete/', views.event_delete, name='event_delete'),
    path('tasks/', views.task_list, name='task_list'),
    path('tasks/<int:task_id>/', views.task_detail, name='task_detail'),
    path('tasks/create/', views.task_create, name='task_create'),
    path('tasks/<int:task_id>/edit/', views.task_edit, name='task_edit'),
    path('tasks/<int:task_id>/delete/', views.task_delete, name='task_delete'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('schedule/', views.schedule_view, name='schedule_view'),
    path('notifications/', views.notification_list, name='notification_list'),
]

stations/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.formats import date_format
from django.db.models.signals import m2m_changed, post_save
from django.dispatch import receiver

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20, blank=True)
    role = models.CharField(max_length=30, choices=[('student', 'Student'), ('employee', 'Employee')], default='student')

    def __str__(self):
        return self.user.username


class Event(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    organizer = models.ForeignKey(UserProfile, related_name='organized_events', on_delete=models.SET_NULL, null=True)
    participants = models.ManyToManyField(UserProfile, related_name='events_attending')

    def __str__(self):
        start_str = self.start_time.strftime("%d.%m.%Y %H:%M")
        end_str = self.end_time.strftime("%d.%m.%Y %H:%M")
        organizer_str = self.organizer.user.username if self.organizer else 'No organizer'
        return f"{self.name} (Start: {start_str}, End: {end_str}) by {organizer_str}"

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    due_date = models.DateTimeField()
    assigned_to = models.ManyToManyField(UserProfile, related_name='tasks')

    def __str__(self):
        due_date_str = date_format(self.due_date, "SHORT_DATETIME_FORMAT")
        assigned_to_names = ', '.join([user.user.username for user in self.assigned_to.all()])
        return f'{self.title} (Due: {due_date_str}) - Assigned to: {assigned_to_names}'

class Comment(models.Model):
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, related_name='comments', on_delete=models.CASCADE, null=True, blank=True)
    task = models.ForeignKey(Task, related_name='comments', on_delete=models.CASCADE, null=True, blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author} on {self.created_at}'

class Schedule(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    events = models.ManyToManyField(Event)

    def __str__(self):
        return f'Schedule for {self.user}'

class Notification(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    message = models.CharField(max_length=255)
    is_read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        display_message = ('"'+self.message[:27] + '..."' if len(self.message) > 30 else '"'+self.message+'"')
        return f'Notification for {self.user} - {"Read" if self.is_read else "Unread"}: {display_message}'

stations/forms.py
from django import forms
from django.forms import DateTimeInput

from .models import Event, Task, Comment, UserProfile, Notification, Schedule


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'description', 'start_time', 'end_time', 'participants']
        widgets = {
            'start_time': DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'assigned_to']
        widgets = {
            'due_date': DateTimeInput(attrs={'type': 'datetime-local'}),
        }

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ['author', 'event', 'task', 'content']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone_number', 'role', 'user']
        widgets = {
            'user': forms.TextInput(attrs={'readonly': True}),
            'role': forms.Select(attrs={'disabled': True}),
        }

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['user'].required = False
        self.fields['role'].required = False

    def save(self, commit=True):
        instance = super(UserProfileForm, self).save(commit=False)
        if commit:
            instance.save()
        return instance

class NotificationForm(forms.ModelForm):
    class Meta():
        model = Notification
        fields = ['user', 'message', 'is_read']

class ScheduleForm(forms.ModelForm):
    class Meta():
        model = Schedule
        fields = ['user', 'events']

stations/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Event, Task, Comment, Schedule, Notification, UserProfile
from .forms import EventForm, TaskForm, CommentForm, UserProfileForm, NotificationForm, ScheduleForm
from django.contrib.auth import views as auth_views

# Главная страница
def index(request):
    return render(request, 'stations/index.html')

# Список событий
@login_required
def event_list(request):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    organized_events = Event.objects.filter(organizer=user_profile)
    participating_events = user_profile.events_attending.all()
    return render(request, 'stations/event_list.html', {
        'organized_events': organized_events,
        'participating_events': participating_events
    })

# Просмотр деталей события
@login_required
def event_detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    comments = Comment.objects.filter(event=event)
    return render(request, 'stations/event_detail.html', {'event': event, 'comments': comments})

# Создание нового события
@login_required
def event_create(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.organizer = request.user.userprofile  # Присваиваем организатора
            event.save()
            form.save_m2m()  # Сохраняем связанные данные ManyToMany

            # Добавление события в расписание организатора
            schedule, created = Schedule.objects.get_or_create(user=request.user.userprofile)
            schedule.events.add(event)

            # Добавление события в расписания всех участников
            for participant in event.participants.all():
                schedule, created = Schedule.objects.get_or_create(user=participant)
                schedule.events.add(event)

            return redirect('event_list')
    else:
        form = EventForm()
    return render(request, 'stations/event_form.html', {'form': form, 'action': 'Create'})


# Редактирование события
@login_required
def event_edit(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
            # Обновление расписаний всех участников
            all_participants = set(event.participants.all())
            previous_participants = set(Schedule.objects.filter(events=event).values_list('user', flat=True))
            new_participants = all_participants - previous_participants
            removed_participants = previous_participants - all_participants

            # Добавляем новых участников
            for participant in new_participants:
                schedule, created = Schedule.objects.get_or_create(user=participant)
                schedule.events.add(event)

            # Удаляем событие у участников, которые были удалены
            for participant in removed_participants:
                schedule = Schedule.objects.get(user=participant)
                schedule.events.remove(event)

            return redirect('event_list')
    else:
        form = EventForm(instance=event)
    return render(request, 'stations/event_form.html', {'form': form, 'action': 'Edit'})


# Удаление события
@login_required
def event_delete(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    if request.method == 'POST':
        event.delete()
        return redirect('event_list')
    return render(request, 'stations/event_confirm_delete.html', {'event': event})

# Список задач
@login_required
def task_list(request):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    assigned_tasks = user_profile.tasks.all()
    return render(request, 'stations/task_list.html', {
        'assigned_tasks': assigned_tasks
    })

# Просмотр деталей задачи
@login_required
def task_detail(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    comments = Comment.objects.filter(task=task)
    return render(request, 'stations/task_detail.html', {'task': task, 'comments': comments})

# Создание новой задачи
@login_required
def task_create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('task_list')
    else:
        form = TaskForm()
    return render(request, 'stations/task_form.html', {'form': form, 'action': 'Create'})

# Редактирование задачи
@login_required
def task_edit(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('task_list')
    else:
        form = TaskForm(instance=task)
    return render(request, 'stations/task_form.html', {'form': form, 'action': 'Edit'})

# Удаление задачи
@login_required
def task_delete(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    if request.method == 'POST':
        task.delete()
        return redirect('task_list')
    return render(request, 'stations/task_confirm_delete.html', {'task': task})

# Профиль пользователя
@login_required
def profile(request):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    tasks = user_profile.tasks.all()
    events = user_profile.events_attending.all()
    # Получите данные пользователя из связанной модели User
    first_name = user_profile.user.first_name
    last_name = user_profile.user.last_name
    email = user_profile.user.email
    # Теперь передайте эти данные в шаблон
    return render(request, 'stations/profile.html', {
        'user_profile': user_profile,
        'tasks': tasks,
        'events': events,
        'first_name': first_name,
        'last_name': last_name,
        'email': email
    })


# Редактирование профиля пользователя
@login_required
def profile_edit(request):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = UserProfileForm(instance=user_profile)
    return render(request, 'stations/profile_form.html', {'form': form, 'action': 'Edit'})

# Просмотр расписания
@login_required
def schedule_view(request):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    schedule = get_object_or_404(Schedule, user=user_profile)
    events = schedule.events.order_by('start_time')

    events_with_roles = []
    for event in events:
        role = 'Organizer' if event.organizer == user_profile else 'Participant'
        events_with_roles.append({'event': event, 'role': role})

    return render(request, 'stations/schedule.html', {
        'schedule': schedule,
        'events_with_roles': events_with_roles
    })

# Уведомления пользователя
@login_required
def notification_list(request):
    notifications = Notification.objects.filter(user__user=request.user)
    return render(request, 'stations/notification_list.html', {'notifications': notifications})

class CustomLoginView(auth_views.LoginView):
    def form_valid(self, form):
        messages.success(self.request, f'Welcome, {form.get_user().username}!')
        return super().form_valid(form)

class CustomLogoutView(auth_views.LogoutView):
    def dispatch(self, request, *args, **kwargs):
        messages.success(request, 'You have been logged out successfully!')
        return super().dispatch(request, *args, **kwargs)

templates/stations/event_confirm_delete.html
<html>
<head>
    <title>Delete Event</title>
</head>
<body>
    <h1>Are you sure you want to delete {{ event.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete">
    </form>
    <a href="{% url 'event_list' %}">Back to Event List</a>
</body>
</html>

templates/stations/event_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ event.name }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="container">
    <h1 class="my-4">{{ event.name }}</h1>
    <p>{{ event.description }}</p>
    <p>Organizer: {{ event.organizer }}</p>
    <p>Start Time: {{ event.start_time }}</p>
    <p>End Time: {{ event.end_time }}</p>
    <h2>Participants</h2>
    <ul class="list-group mb-4">
        {% for participant in event.participants.all %}
            <li class="list-group-item">{{ participant.user.username }}</li>
        {% endfor %}
    </ul>
    <h2>Comments</h2>
    <ul class="list-group mb-4">
        {% for comment in comments %}
            <li class="list-group-item">{{ comment.author.user.username }}: {{ comment.content }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'event_edit' event.id %}" class="btn btn-primary">Edit Event</a>
    <form action="{% url 'event_delete' event.id %}" method="post" class="d-inline">
        {% csrf_token %}
        <input type="submit" value="Delete Event" class="btn btn-danger">
    </form>
    <a href="{% url 'event_list' %}" class="btn btn-secondary ml-2">Back to Event List</a>
</body>
</html>

templates/stations/event_form.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ action }} Event</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
</head>
<body class="container">
    <h1 class="my-4">{{ action }} Event</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">{{ action }} Event</button>
        <a href="{% url 'event_list' %}" class="btn btn-secondary ml-2">Back to Event List</a>
    </form>

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        flatpickr("#id_start_time", {enableTime: true, dateFormat: "Y-m-d H:i"});
        flatpickr("#id_end_time", {enableTime: true, dateFormat: "Y-m-d H:i"});
    </script>
</body>
</html>

templates/stations/event_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Event List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="container">
    <h1 class="my-4">Events</h1>

    <h2>Organized Events</h2>
    {% if organized_events %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Event</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                </tr>
            </thead>
            <tbody>
                {% for event in organized_events %}
                    <tr>
                        <td><a href="{% url 'event_detail' event.id %}">{{ event.name }}</a></td>
                        <td>{{ event.start_time|date:"d.m.Y H:i" }}</td>
                        <td>{{ event.end_time|date:"d.m.Y H:i" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No events organized by you.</p>
    {% endif %}

    <h2>Participating Events</h2>
    {% if participating_events %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Event</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                </tr>
            </thead>
            <tbody>
                {% for event in participating_events %}
                    <tr>
                        <td><a href="{% url 'event_detail' event.id %}">{{ event.name }}</a></td>
                        <td>{{ event.start_time|date:"d.m.Y H:i" }}</td>
                        <td>{{ event.end_time|date:"d.m.Y H:i" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No events you're participating in.</p>
    {% endif %}

    <a href="{% url 'event_create' %}" class="btn btn-primary">Create New Event</a>
    <a href="{% url 'index' %}" class="btn btn-secondary ml-2">Back to Home</a>
</body>
</html>

templates/stations/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Campus Event Manager</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="container">
    <h1 class="my-4">Welcome to Campus Event Manager</h1>
    {% if messages %}
        <div class="alert alert-info" role="alert">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <nav class="mb-4">
        <ul class="nav nav-pills">
            <li class="nav-item"><a class="nav-link" href="{% url 'event_list' %}">Events</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'task_list' %}">Tasks</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">Profile</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'schedule_view' %}">Schedule</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'notification_list' %}">Notifications</a></li>
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout ({{ user.username }})</a></li>
                <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                    {% csrf_token %}
                </form>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
            {% endif %}
        </ul>
    </nav>
</body>
</html>

templates/stations/notification_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Notifications</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="container">
    <h1 class="my-4">Notifications</h1>
    <ul class="list-group mb-4">
        {% for notification in notifications %}
            <li class="list-group-item">
                {{ notification.message }} -
                {% if notification.is_read %}
                    Read
                {% else %}
                    Unread
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'index' %}" class="btn btn-secondary ml-2">Back to Home</a>
</body>
</html>

templates/stations/profile.html
<!DOCTYPE html>
<html>
<head>
    <title>Profile</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="container">
    <h1 class="my-4">{{ user_profile.user.username }}'s Profile</h1>
    <div>
        <strong>First Name:</strong> {{ first_name }}
    </div>
    <div>
        <strong>Last Name:</strong> {{ last_name }}
    </div>
    <div>
        <strong>Email:</strong> {{ email }}
    </div>
    <div>
        <strong>Phone Number:</strong> {{ user_profile.phone_number }}
    </div>
    <div>
        <strong>Role:</strong> {{ user_profile.get_role_display }}
    </div>
    <h2>Tasks</h2>
    <ul class="list-group mb-4">
        {% for task in tasks %}
            <li class="list-group-item"><a href="{% url 'task_detail' task.id %}">{{ task.title }}</a></li>
        {% endfor %}
    </ul>
    <h2>Events</h2>
    <ul class="list-group mb-4">
        {% for event in events %}
            <li class="list-group-item"><a href="{% url 'event_detail' event.id %}">{{ event.name }}</a></li>
        {% endfor %}
    </ul>
    <a href="{% url 'profile_edit' %}" class="btn btn-primary">Edit Profile</a>
    <a href="{% url 'index' %}" class="btn btn-secondary ml-2">Back to Home</a>
</body>
</html>

templates/stations/profile_form.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ action }} Profile</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
</head>
<body class="container">
    <h1 class="my-4">{{ action }} Profile</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">{{ action }} Profile</button>
    </form>
</body>
</html>


templates/stations/schedule.html
<!DOCTYPE html>
<html>
<head>
    <title>Schedule</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="container">
    <h1 class="my-4">Schedule for {{ schedule.user.user.username }}</h1>
    <h2>Events</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Event</th>
                <th>Day</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Role</th>
            </tr>
        </thead>
        <tbody>
            {% for event_with_role in events_with_roles %}
                <tr>
                    <td><a href="{% url 'event_detail' event_with_role.event.id %}">{{ event_with_role.event.name }}</a></td>
                    <td>{{ event_with_role.event.start_time|date:"d.m.Y" }}</td>
                    <td>{{ event_with_role.event.start_time|date:"H:i" }}</td>
                    <td>{{ event_with_role.event.end_time|date:"H:i" }}</td>
                    <td>{{ event_with_role.role }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'index' %}" class="btn btn-secondary ml-2">Back to Home</a>
</body>
</html>

templates/stations/task_confirm_delete.html
<html>
<head>
    <title>Delete Task</title>
</head>
<body>
    <h1>Are you sure you want to delete {{ task.title }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete">
    </form>
    <a href="{% url 'task_list' %}">Back to Task List</a>
</body>
</html>

templates/stations/task_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ task.title }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="container">
    <h1 class="my-4">{{ task.title }}</h1>
    <p>{{ task.description }}</p>
    <p>Due Date: {{ task.due_date }}</p>
    <h2>Assigned To</h2>
    <ul class="list-group mb-4">
        {% for assignee in task.assigned_to.all %}
            <li class="list-group-item">{{ assignee.user.username }}</li>
        {% endfor %}
    </ul>
    <h2>Comments</h2>
    <ul class="list-group mb-4">
        {% for comment in comments %}
            <li class="list-group-item">{{ comment.author.user.username }}: {{ comment.content }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'task_edit' task.id %}" class="btn btn-primary">Edit Task</a>
    <form action="{% url 'task_delete' task.id %}" method="post" class="d-inline">
        {% csrf_token %}
        <input type="submit" value="Delete Task" class="btn btn-danger">
    </form>
    <a href="{% url 'task_list' %}" class="btn btn-secondary ml-2">Back to Task List</a>
</body>
</html>

templates/stations/task_form.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ action }} Task</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
</head>
<body class="container">
    <h1 class="my-4">{{ action }} Task</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">{{ action }} Task</button>
        <a href="{% url 'task_list' %}" class="btn btn-secondary ml-2">Back to Task List</a>
    </form>
</body>
</html>

templates/stations/task_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Task List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body class="container">
    <h1 class="my-4">Tasks</h1>
    {% if assigned_tasks %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Due Date</th>
                </tr>
            </thead>
            <tbody>
                {% for task in assigned_tasks %}
                    <tr>
                        <td><a href="{% url 'task_detail' task.id %}">{{ task.title }}</a></td>
                        <td>{{ task.due_date|date:"d.m.Y H:i" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No tasks assigned to you.</p>
    {% endif %}
    <a href="{% url 'task_create' %}" class="btn btn-primary">Create New Task</a>
    <a href="{% url 'index' %}" class="btn btn-secondary ml-2">Back to Home</a>
</body>
</html>